### ISSUE TITLE
Why depend on 27.1?

### ISSUE THREAD

**Issue by wasamasa** [fosskers/streak#2]
I've run [package-lint](https://github.com/purcell/package-lint) on the sources to see why the package needs 27.1 and there are no hard requirements for it:

- `time-convert` (introduced in 27.1): Your usage of it is equivalent to `(current-seconds)`
- `xdg-cache-home` (introduced in 26.1): Emacs packages commonly just place their stuff inside `user-emacs-directory`. If you feel strongly about using XDG support when available, use conditional code testing `(require 'xdg nil t)` instead.
- `when-let` (introduced in 25.1): It's a combination of `let` and `when`. You save one line of typing here.

I wouldn't go below Emacs 24.5 support-wise as that's the version in the oldest supported Debian Stretch release.

**Comment by fosskers** [comment]
Thanks for bringing up these points!

> time-convert

`(current-seconds)` does not seem to be present in Emacs 28 (the version I use and the only one I'm testing on).

> `xdg-cache-home`

I was asked to do it this way by the Melpa maintainers. I'm generally in favour of respecting XDG.

> when-let

I practice minimalist coding, so in general if there are two lines that can be one, I make it one.

> Debian Stretch

It's an open question in many software communities as to what degree back-compat should be respected. Or said a different way, how long should we deny ourselves access to the newest APIs just to appease hypothetical legacy users? You might notice the `TODO` item above `streak-file`:
```lisp
;; TODO Use `file-name-concat' once Emacs 28 is the lowest supported version.
```
In general, I'm of the stance that we should adopt new APIs _as soon as is reasonable_ with respect to said hypothetical legacy users. I don't think it fair for the majority to be held hostage by a hypothetical minority. To me, even Emacs 26 users should be doing their best to upgrade to 27.

That said, I'd be happy to maneuver the lower bound to 26 if we can figure out a replacement for `time-convert` that works on 26/27/28. Any ideas?

**Comment by wasamasa** [comment]
> `(current-seconds)` does not seem to be present in Emacs 28 (the version I use and the only one I'm testing on).

Sorry, I meant `(current-time)`.

> I practice minimalist coding, so in general if there are two lines that can be one, I make it one.

That is one way of interpreting minimalism. I practice minimizing the dependencies in my projects. Given the slow release pace of Emacs itself, Emacs versions qualify as well.

> It's an open question in many software communities as to what degree back-compat should be respected. Or said a different way, how long should we deny ourselves access to the newest APIs just to appease hypothetical legacy users? You might notice the `TODO` item above `streak-file`:
> 
> ```lisp
> ;; TODO Use `file-name-concat' once Emacs 28 is the lowest supported version.
> ```

Yeah, I did. It seems kind of silly to increase version requirements because it appears to be equivalent to using the recommended `(concat (file-name-as-directory dir) file)` repeatedly.

> In general, I'm of the stance that we should adopt new APIs _as soon as is reasonable_ with respect to said hypothetical legacy users. I don't think it fair for the majority to be held hostage by a hypothetical minority. To me, even Emacs 26 users should be doing their best to upgrade to 27.

Take a look at what the commonly used distros ship. I like https://pkgs.org for that. As much as I like up-to-date software, I'm not pretending everyone else uses a bleeding edge distro or compiles everything from source. Most people in the world do not care about software as much as I do and consider updates an unnecessary burden.

> That said, I'd be happy to maneuver the lower bound to 26 if we can figure out a replacement for `time-convert` that works on 26/27/28. Any ideas?

Yes, `(current-time)` has been available since a very long time.

**Comment by fosskers** [comment]
Thanks for the advice, I did take a look at what Emacs versions that various projects in the ecosystem expect. The results are here: https://gist.github.com/fosskers/5b326fbbc2b8fef2f55f64467dbb9f74

Note that Debian Stable is now up to 27, which seems to be the criteria for Spacemacs (although it seems they haven't quite bumped up yet). Doom expects 27 for a number of good reasons, as can be seen in the commit linked in the chart. Otherwise I'm mainly looking at what Ubuntu LTS provides, namely 26. Lower than 26 I will thus consider "hostage by a minority" as I said above. 

So I'm somewhat willing (see below) to dropping `streak`'s Emacs requirement down to 26, except that a call to `(current-time)` is not a drop-in replacement for `(time-convert nil 'integer)`. Further, Emacs doesn't recommend manual manipulation of the result of `(current-time)` at all. From the Manual: 

> Although traditionally Lisp timestamps were integer pairs, their form has evolved and programs ordinarily should not depend on the current default form. If your program needs a particular timestamp form, you can use the time-convert function to convert it to the needed form.

and

> Although the timestamp takes the form (high low micro pico) in the current Emacs release, this is planned to change in a future Emacs version. 

If the future-proof approach recommended by Emacs itself is to use `time-convert`, then that seems to most responsible path to take, even if it means stopping at 27. I've looked for examples of converting the result of `current-time` into a plain integer via manual manipulation (the unrecommended way), but I haven't been able to find one.

**Comment by fosskers** [comment]
Perhaps something could be done with `(time-subtract)`, although I've already been using raw integers for everything.

**Comment by fosskers** [comment]
In the end, given that Emacs 28 is right around the corner (many people already use it), that `streak` is a very small and very particular package for particular people, and that `time-convert` is considered idiomatic by Emacs, I'm going to stick with Emacs 27 as a lower bound.

Thank you for your time and for bringing this to my attention!
